version: '3.1'

services:
  srvmongo:
    image: mongo:4.2-bionic
    ports:
        - 47017:27017
    volumes: 
      - /data/db/testing:/data/db
    tty: true
    stdin_open: true
    container_name: ctn_testdb